name: sequelize_orm_example
description: Example project demonstrating sequelize_orm usage.
version: 1.0.0
resolution: workspace

environment:
  sdk: ^3.10.0

dependencies:
  sequelize_orm:
    path: ../packages/sequelize_orm
  dotenv: ^4.2.0
  meta: ^1.17.0


dev_dependencies:
  sequelize_orm_generator:
    path: ../packages/sequelize_orm_generator
  build_runner: ^2.10.4
  lints: ^6.0.0
