name: sequelize_dart_annotations
description: Annotations for sequelize_dart code generation. Platform-independent.
version: 1.0.0

environment:
  sdk: ^3.9.2

dependencies: {}

dev_dependencies:
  lints: ^6.0.0
