name: sequelize_dart_annotations
description: Annotations for sequelize_dart code generation. Platform-independent.
version: 1.0.0
resolution: workspace

environment:
  sdk: ^3.9.2

dependencies:
  sequelize_dart:
    path: ../sequelize_dart

dev_dependencies:
  lints: ^6.0.0
