name: sequelize_orm
description: A Dart ORM for Sequelize.js integration with code generation support.
version: 1.0.0
resolution: workspace

environment:
  sdk: ^3.9.2

dependencies:
  meta: ^1.17.0
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0

platforms:
  linux:
  macos:
  web:
  windows: