name: sequelize_orm_generator
description: Code generator for sequelize_orm package.
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.9.2

dependencies:
  analyzer: ^9.0.0
  build: ^4.0.3
  glob: ^2.1.2
  path: ^1.9.0
  source_gen: ^4.1.1
  yaml: ^3.1.3
  sequelize_orm:
    path: ../sequelize_orm

dev_dependencies:
  build_runner: ^2.10.4
  build_test: ^3.5.4
  lints: ^6.0.0
  test: ^1.25.6











