name: sequelize_orm_generator
description: >-
  Code generator for sequelize_orm. Generates type-safe model classes, query
  builders, and a centralized model registry from annotated Dart classes using
  build_runner.
version: 0.1.4
repository: https://github.com/crazidev/sequelize_orm_dart
resolution: workspace

topics:
  - orm
  - code-generation
  - build-runner
  - database
  - sql

environment:
  sdk: ^3.6.0

dependencies:
  analyzer: ">=9.0.0 <11.0.0"
  build: ">=3.0.0 <5.0.0"
  glob: ^2.1.2
  path: ^1.9.0
  source_gen: ">=3.0.0 <5.0.0"
  yaml: ^3.1.3
  sequelize_orm: ^0.1.4

dev_dependencies:
  build_runner: ^2.10.4